### ISSUE TITLE
Force close when trying to do contact lookup

### ISSUE THREAD

**Issue by aquatix** [G00fY2/k-9_material_design#3]
First, thanks for this awesome fork!

On 5.207.3, the app crashes when typing a name in the To on a new email. I guess it has to do with address book access rights, but as I did install 5.207.1 and upgraded from there, it never asked permission in first run.

**Comment by G00fY2** [comment]
Thanks for the report!
But this isn't caused by a new bug. You need to grant K-9 Material Fork the permission to access your contacts (as well as your storage to save attachments e.g.). I already integrated the permissions request dialog into version 5.207.3. 😉 

This is a result of moving targetSDK to greater than 22 (Lollipop). With targeting the latest SDK level, permissions need to be granted from the user at runtime (further informations: https://developer.android.com/training/permissions/requesting.html).

**Comment by aquatix** [comment]
Yes, that's why I opened this bug: on 5.207.3 I do not get that dialog, and it crashes.

**Comment by G00fY2** [comment]
Sorry, seems like I didn't pay enough attention to your report.

The permission request should appear on first start and when going into your accounts list. There you don't see it? What Android Version are you running? Ofc you can still grant permissions manually in the android app settings.

PS: I won't integrate dynamically catching the runtime permission requests because this would result in many changes to the mail logic. My goal is to keep my fork compatible to future updates.

**Comment by aquatix** [comment]
I'm seeing it when I start composing a new message and start typing a name in the To input field. When K-9 tries to complete it from the address book, it force closes.

I'm running stock 7.1.2 on a Nexus 6P.

And of course I can do it manually, but I'd like to help you make the fork more robust :) Maintainability is a pre, so I totally see your other points.

Thanks again for even making it :)

**Comment by G00fY2** [comment]
I know when/why the error occurs.

But do you get the permission request dialog or the alert that permissions are required when going into the **accounts list**? You should at least see the message "Both contact and storage permission are needed for K-9 to work properly". This dialog does not get triggered dynamically when the actual permission is needed (e.g. check your contacts to autocomplete recipients). 

I get this message on my Pixel running Nougat 7.1.2 and on my HTC One running LinageOS 14.1 when storage or contacts permission is not granted.

**Comment by aquatix** [comment]
My bad, I misunderstood. Yes, when I navigate to the accounts list, I do indeed get two permission requests, one for the contacts and one for storage, so that works like intended, thanks.

And of course, now I gave it permissions, everything is fine.

OK, that's clear then :) Thanks for your time and I'm looking forward to further updates. It's my primary mobile email client and doing a great job.

**Comment by G00fY2** [comment]
Yeah, it's more a workaround (took me around 10 lines of code) to give the user a chance to grant permissions at startup/without leaving the app. Normally the idea is to ask the user while the permission is needed at runtime. But this would result in too many changes in the code, as I said. 😄
