### ISSUE TITLE
Sync automatically disabled

### ISSUE THREAD

**Issue by jerryn70** [G00fY2/k-9_material_design#5]
I am not getting push notifications when ne email arrives. When I open the app it shows sync disabled . I have turned sync settings to always and turn off battery optimization. But no use. 

K9 version 208
Device moto x play stock naugat 7.1

**Comment by G00fY2** [comment]
Please try the same with default K9. Settings can be exported and reimported between both vesions.

Only difference my fork maybe has regarding push is the higher target SDK which can possibly change some behaviours. Other than that my fork only changes visuals.

**Comment by jerryn70** [comment]
@G00fy2 That tip didn't worked. After every doze period i need to open the app then only it will push .

Today I tried version 302 from github, and that works great. Can you materialize that version ? It will be great if do it

**Comment by G00fY2** [comment]
In 302 [nearly every class](https://github.com/k9mail/k-9/compare/5.208...5.302#files_bucket) was touched (also layout files).
I won't be able to merge this version. Doesn't think I will have time to manually merge all changes any time soon.

**Comment by avently** [comment]
@G00fY2 it's happened because you made unnecessary changes like indentation in xml files and reposition of import statements in java files. It makes your work much harder. I don't understand why you did it but we have what we have. Maybe a solution here can be to make PRs to original repo with material design changes. All design examples are already exists so the idea is to write a code to implement such look and feel. You can coordinate your work with k9 maintainers. I think they will be happy to know that you are making the cool design.  Do you like the idea?

**Comment by G00fY2** [comment]
@avently I doubt you took the time to be able to judge why I (had to) made some of the changes and what I did in detail.
Since the app only has a few screen, the main layout files I changed are only 3-4. Thats definitely not the problem and I wouldn't even need to merge those files for a first version.
It's also not a problem to have different indentation (only changed those in xml) or order in your imports or stuff like that. IntelliJ/AS has a powerful merge tool and detects these changes. 

But as you can easily see when you [diff my fork](https://github.com/k9mail/k-9/compare/5.208...G00fY2:5.2-MAINT#files_bucket) I had to change a lot of java files to port them to appcompat library, add the color theming, change the contact badges, update target SDK, add runtime permissions.

In the latest official release most of the classes in the original branch have different variable naming, formatting (linebreaks within if else statements) and so on.
So now I have my changes and variables naming changes from the K9 team e.g. in the same line of code. There is no other way to manually jump into the source file and rewrite stuff... And that has nothing to do with the points you mentioned.

I also don't think this issue is the right place to discuss this topic.

**Comment by avently** [comment]
@G00fY2 first part of my comment (about what you did) is not so important as the second part (about what you can do). And I'm not judging. I saw a great fork and a problem (=it's not easy to maintain such a "live" project) and said about possible solution. That's it. You didn't answer on it. ok.

**Comment by G00fY2** [comment]
Guess they will rewrite their view logic or at least hope so because atm the code is really ugly. So there is no real sense for me to send PR with my current work.

Yeah, maybe I find time to work on the official version. But I haven't get in contact with them and have some other projects im working on. Time will tell.

Still not sure about what problem youre talking. I actually started this fork because the other material fork is a **real** problem and isn't linked to the origin branch at all.
